project_id = "sfbowejaevlmhcvsxhbk"

[functions.gerar-campanha]
verify_jwt = false

[functions.gerar-banners]
verify_jwt = false

[functions.get-render-status]
verify_jwt = false

[functions.criar-animacao-premium]
verify_jwt = false

[functions.gerar-hero-ia]
verify_jwt = false

[functions.criar-video-ia]
verify_jwt = false

[functions.criar-video-ia-multi]
verify_jwt = false

[functions.get-video-job-status]
verify_jwt = false
