import test from 'node:test'
import assert from 'node:assert/strict'
import { handleVideoSocialPublish, type VideoDestination, type VideoSocialPublishDependencies } from './runtime.ts'

const sourceId = '6b66b517-8fea-4b62-a180-89f64c418cba'
const ownerId = '0d41421b-a063-4320-bba8-0f2f840c5fa1'
const captions = ['Texto 1 exato.', 'Texto 2 exato.\nSem alteração.', 'Texto 3 exato.']
const request = (destinations: VideoDestination[], option = 1, action: 'publish' | 'recovery' = 'publish', captionSnapshot?: string) => new Request('https://local.invalid/social-publish-video', { method:'POST', headers:{Authorization:'Bearer owner-session','Content-Type':'application/json'}, body:JSON.stringify({action,source:{type:'video_imobiliario',id:sourceId},media_asset_id:sourceId,option_id:`smart-tour-caption-option-${option}`,...(captionSnapshot === undefined ? {} : {caption_snapshot:captionSnapshot}),destinations}) })
const studioRequest = (sourceType: string, destinations: VideoDestination[], option = 1, action: 'publish' | 'recovery' = 'publish') => new Request('https://local.invalid/social-publish-video', { method:'POST', headers:{Authorization:'Bearer owner-session','Content-Type':'application/json'}, body:JSON.stringify({action,source:{type:sourceType,id:sourceId},media_asset_id:sourceId,option_id:`studio-caption-option-${option}`,caption_snapshot:captions[option-1],destinations}) })

function context(outcomes: Partial<Record<VideoDestination, string>> = {}) {
  const calls = { resolved:0, created:[] as Array<Record<string, unknown>>, claimed:[] as string[], leased:[] as string[], workers:[] as VideoDestination[] }
  const jobs = new Map<VideoDestination,{id:string,status:string}>()
  const dependencies: VideoSocialPublishDependencies = {
    authenticate: async token => token === 'owner-session' ? {id:ownerId} : null,
    resolveIntent: async (_owner,input) => { calls.resolved += 1; return {sourceType:input.sourceType,sourceId:input.sourceId,mediaAssetId:input.mediaAssetId,optionId:input.optionId,captionSnapshot:input.captionSnapshot ?? captions[Number(input.optionId.at(-1))-1],connectionId:'9bc6ad60-9021-4fda-a8f9-da6756f41cba',bucket:'studio-videos',objectPath:`${ownerId}/${sourceId}/smart-tour.mp4`,contentType:'video/mp4',contentLength:1234} },
    deriveIdempotencyKey: async (_owner,intent,destination) => `${destination}-${intent.optionId}`,
    createOrReuseJob: async input => { calls.created.push(input); const existing=jobs.get(input.destination); if(existing)return{id:existing.id,status:existing.status,reused:true}; const job={id:input.destination==='instagram'?'11111111-1111-4111-8111-111111111111':'22222222-2222-4222-8222-222222222222',status:'queued'}; jobs.set(input.destination,job); return{id:job.id,status:job.status,reused:false} },
    findJob: async (_owner,_key,destination) => { const job=jobs.get(destination); return job?{jobId:job.id,destination,status:job.status,externalPostId:job.status==='published'?`${destination}-post`:null,externalPostLink:null,publicErrorCode:job.status==='failed'?'social_publish_failed':null}:null },
    claimJob: async jobId => {calls.claimed.push(jobId);return{jobId,claimToken:'33333333-3333-4333-8333-333333333333'}},
    createLease: async input => {calls.leased.push(input.jobId);assert.equal(input.intent.contentType,'video/mp4');return true},
    hashCapability: async ()=>'a'.repeat(64), randomCapability:()=> 'x'.repeat(43),
    invokeWorker: async input => {calls.workers.push(input.destination);const job=jobs.get(input.destination)!;job.status=outcomes[input.destination]||'published';return{ok:job.status==='published'}},
  }
  return {calls,jobs,dependencies}
}

for (const option of [1,2,3]) test(`Texto ${option} persiste caption_snapshot exato`, async()=>{const c=context();assert.equal((await handleVideoSocialPublish(request(['instagram'],option),c.dependencies)).status,200);assert.equal((c.calls.created[0].intent as {captionSnapshot:string}).captionSnapshot,captions[option-1])})
test('Vídeo Imobiliário aceita legenda editada, substituída e vazia exatamente',async()=>{for(const captionSnapshot of ['Texto editado.','Novo vídeo ✨\nVisite hoje.','']){const c=context();assert.equal((await handleVideoSocialPublish(request(['instagram'],1,'publish',captionSnapshot),c.dependencies)).status,200);assert.equal((c.calls.created[0].intent as {captionSnapshot:string}).captionSnapshot,captionSnapshot)}})
test('somente Instagram cria um job/worker',async()=>{const c=context();const body=await(await handleVideoSocialPublish(request(['instagram']),c.dependencies)).json();assert.deepEqual(c.calls.workers,['instagram']);assert.equal(body.status,'published');assert.equal(body.smart_tokens,0)})
test('somente Facebook cria um job/worker',async()=>{const c=context();await handleVideoSocialPublish(request(['facebook']),c.dependencies);assert.deepEqual(c.calls.workers,['facebook'])})
test('ambos são independentes e preservam sucesso parcial',async()=>{const c=context({facebook:'failed'});const body=await(await handleVideoSocialPublish(request(['instagram','facebook']),c.dependencies)).json();assert.equal(body.status,'partial_success');assert.equal(body.results.find((item:{destination:string})=>item.destination==='instagram').status,'published');assert.equal(body.results.find((item:{destination:string})=>item.destination==='facebook').status,'failed')})
test('replay published não cria claim, lease ou duplicação',async()=>{const c=context();c.jobs.set('instagram',{id:'11111111-1111-4111-8111-111111111111',status:'published'});await handleVideoSocialPublish(request(['instagram']),c.dependencies);assert.equal(c.calls.claimed.length,0);assert.equal(c.calls.leased.length,0);assert.equal(c.calls.workers.length,0)})
test('recovery é read-only e não resolve mídia nem chama worker',async()=>{const c=context();c.jobs.set('facebook',{id:'22222222-2222-4222-8222-222222222222',status:'published'});const body=await(await handleVideoSocialPublish(request(['facebook'],1,'recovery'),c.dependencies)).json();assert.equal(body.results[0].external_post_id,'facebook-post');assert.equal(c.calls.created.length,0);assert.equal(c.calls.workers.length,0);assert.equal(c.calls.resolved,0)})
test('owner/sessão e identidade inválida falham fechados',async()=>{const c=context();assert.equal((await handleVideoSocialPublish(new Request('https://local.invalid',{method:'POST',body:'{}'}),c.dependencies)).status,401);const wrong=new Request('https://local.invalid',{method:'POST',headers:{Authorization:'Bearer owner-session'},body:JSON.stringify({action:'publish',source:{type:'video_imobiliario',id:sourceId},media_asset_id:'different',option_id:'smart-tour-caption-option-1',destinations:['instagram']})});assert.equal((await handleVideoSocialPublish(wrong,c.dependencies)).status,400);assert.equal(c.calls.created.length,0)})
test('resposta nunca expõe capability, claim ou segredo',async()=>{const c=context();const body=await(await handleVideoSocialPublish(request(['instagram','facebook']),c.dependencies)).text();assert.doesNotMatch(body,/capability|claim_token|access_token|ciphertext|secret/i)})
for (const sourceType of ['studio_ia_commercial','studio_ia_creative','studio_ia_carousel']) test(`${sourceType} usa o mesmo runtime com snapshot exato`,async()=>{const c=context();const response=await handleVideoSocialPublish(studioRequest(sourceType,['instagram','facebook'],2),c.dependencies);assert.equal(response.status,200);assert.equal((c.calls.created[0].intent as {sourceType:string}).sourceType,sourceType);assert.equal((c.calls.created[0].intent as {captionSnapshot:string}).captionSnapshot,captions[1]);assert.deepEqual(c.calls.workers,['instagram','facebook'])})
