import test from 'node:test'
import assert from 'node:assert/strict'
import { createInstagramVideoContainer } from '../_shared/instagram/publish-client.ts'
import { publishFacebookPageVideo } from '../_shared/facebook/publish-client.ts'
import { handleInstagramJobPublish, type InstagramJobPublishDependencies } from '../social-publish-instagram-job/runtime.ts'
import { handleFacebookJobPublish, type FacebookJobPublishDependencies } from '../social-publish-facebook-job/runtime.ts'

const jobId='cad35ada-6bef-4e0c-9f22-80433a36f60b', claim='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', cap='0123456789abcdef0123456789abcdef0123456789a', hash='hash', caption='Legenda exata do Vídeo Imobiliário.'
const request=()=>new Request('https://local.invalid',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_id:jobId,claim_token:claim,lease_capability:cap})})

function instagramContext(statuses=['FINISHED'] as Array<'IN_PROGRESS'|'FINISHED'|'ERROR'|'EXPIRED'>){
  const calls={container:0,publish:0,reconcile:0}
  const dependencies:InstagramJobPublishDependencies={
    expectedContentType:'video/mp4',expectedInstagramUsername:null,getJob:async()=>({id:jobId,userId:'owner',connectionId:'connection',caption,claimToken:claim}),getLease:async()=>({id:'lease',jobId,capabilityHash:hash,expiresAt:'2026-09-01T12:00:00.000Z',contentType:'video/mp4',contentLength:4096}),hashCapability:async()=>hash,validateLeaseUrl:async()=>true,getActiveAccount:async()=>({instagramUserId:'17841400000000000',instagramUsername:'conta_selecionada',pageName:'Página selecionada',pageAccessToken:'private'}),validateConnection:async()=>true,recordConnectionValidation:async()=>true,createContainer:async input=>{calls.container++;assert.equal(input.caption,caption);return'18000000000000001'},startContainerPolling:async()=>true,getContainerStatus:async()=>statuses.shift()||'IN_PROGRESS',recordPoll:async()=>true,deferPollTimeout:async()=>true,publishContainer:async()=>{calls.publish++;return'18000000000000002'},markReconciliationRequired:async()=>{calls.reconcile++;return true},getPostDetail:async()=>({id:'18000000000000002',permalink:'https://www.instagram.com/p/video/',caption,username:'conta_selecionada'}),completeJob:async()=>true,sleep:async()=>undefined,now:()=>Date.parse('2026-08-31T12:00:00.000Z'),maxPolls:statuses.length||1,pollIntervalMs:1,buildLeaseUrl:value=>`https://lease.invalid/${value}`,
  }
  return{calls,dependencies}
}

function facebookContext(){
  const calls={post:0,reconcile:0}
  const dependencies:FacebookJobPublishDependencies={
    expectedContentTypes:['video/mp4'],getJob:async()=>({id:jobId,userId:'owner',connectionId:'connection',socialAccountId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',platform:'facebook',caption,claimToken:claim}),getLease:async()=>({id:'lease',jobId,capabilityHash:hash,expiresAt:'2026-09-01T12:00:00.000Z',contentType:'video/mp4',contentLength:4096}),hashCapability:async()=>hash,validateLeaseUrl:async()=>true,getActiveAccount:async()=>({socialAccountId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',pageId:'123456789012345',pageName:'SmartCorretorAI',pageAccessToken:'private',userAccessToken:'private-user'}),validateCapability:async()=>true,recordConnectionValidation:async()=>true,beginExternalPublish:async()=>true,publishPhoto:async input=>{calls.post++;assert.equal(input.caption,caption);return{postId:'987654321098765',permalink:'https://www.facebook.com/123456789012345/videos/987654321098765'}},completeJob:async()=>true,markReconciliationRequired:async()=>{calls.reconcile++;return true},buildLeaseUrl:value=>`https://lease.invalid/${value}`,now:()=>Date.parse('2026-08-31T12:00:00.000Z'),
  }
  return{calls,dependencies}
}

test('Instagram vídeo aceita somente lease MP4, espera FINISHED e publica uma vez',async()=>{const c=instagramContext(['IN_PROGRESS','FINISHED']);const response=await handleInstagramJobPublish(request(),c.dependencies);assert.equal(response.status,200);assert.equal(c.calls.container,1);assert.equal(c.calls.publish,1)})
test('Instagram timeout mantém o mesmo container e não publica',async()=>{const c=instagramContext(['IN_PROGRESS']);c.dependencies.maxPolls=1;const response=await handleInstagramJobPublish(request(),c.dependencies);assert.equal(response.status,504);assert.equal(c.calls.container,1);assert.equal(c.calls.publish,0)})
test('Facebook vídeo faz um único POST depois do guard irreversível',async()=>{const c=facebookContext();assert.equal((await handleFacebookJobPublish(request(),c.dependencies)).status,200);assert.equal(c.calls.post,1)})
test('Facebook timeout ambíguo não repete e exige reconciliation',async()=>{const c=facebookContext();c.dependencies.publishPhoto=async()=>{c.calls.post++;throw new Error('timeout')};assert.equal((await handleFacebookJobPublish(request(),c.dependencies)).status,502);assert.equal(c.calls.post,1);assert.equal(c.calls.reconcile,1)})
test('worker de vídeo rejeita lease de imagem antes da Meta',async()=>{const i=instagramContext();i.dependencies.getLease=async()=>({id:'lease',jobId,capabilityHash:hash,expiresAt:'2026-09-01T12:00:00.000Z',contentType:'image/jpeg',contentLength:4096});assert.equal((await handleInstagramJobPublish(request(),i.dependencies)).status,409);assert.equal(i.calls.container,0);const f=facebookContext();f.dependencies.getLease=async()=>({id:'lease',jobId,capabilityHash:hash,expiresAt:'2026-09-01T12:00:00.000Z',contentType:'image/jpeg',contentLength:4096});assert.equal((await handleFacebookJobPublish(request(),f.dependencies)).status,409);assert.equal(f.calls.post,0)})
test('cliente Instagram cria container de vídeo hospedado sem alterar caption',async()=>{let calls=0;const id=await createInstagramVideoContainer({graphApiVersion:'v26.0',instagramUserId:'17841400000000000',pageAccessToken:'private',videoUrl:'https://lease.invalid/opaque',caption,fetcher:async(input,init)=>{calls++;assert.equal(String(input),'https://graph.facebook.com/v26.0/17841400000000000/media');const body=init?.body as URLSearchParams;assert.equal(body.get('media_type'),'REELS');assert.equal(body.get('video_url'),'https://lease.invalid/opaque');assert.equal(body.get('caption'),caption);return Response.json({id:'18000000000000001'})}});assert.equal(id,'18000000000000001');assert.equal(calls,1)})
test('cliente Facebook usa somente POST /{page_id}/videos e description exata',async()=>{let calls=0;const result=await publishFacebookPageVideo({graphApiVersion:'v26.0',pageId:'123456789012345',pageAccessToken:'private',videoUrl:'https://lease.invalid/opaque',caption,fetcher:async(input,init)=>{calls++;assert.equal(String(input),'https://graph.facebook.com/v26.0/123456789012345/videos');assert.equal(init?.method,'POST');const body=init?.body as URLSearchParams;assert.equal(body.get('file_url'),'https://lease.invalid/opaque');assert.equal(body.get('description'),caption);return Response.json({id:'987654321098765'})}});assert.equal(result.postId,'987654321098765');assert.equal(calls,1)})
