import test from 'node:test'
import assert from 'node:assert/strict'
import { OFFICIAL_MATRIX, buildPropertyContext, buildSmartTourPrompt, normalizeGeneration, validateSmartTourRequest } from '../index.ts'
const property = {purpose:'sale',type:'Apartamento',city:'São Paulo',district:'Moema',highlights:['Varanda gourmet']}
test('official matrix has all 19 supported combinations',()=>assert.equal(OFFICIAL_MATRIX.length,19))
for (const [index,generation] of OFFICIAL_MATRIX.entries()) test(`matrix combination ${index + 1} builds without contradictions`,()=>assert.doesNotThrow(()=>buildSmartTourPrompt({generation,property,selectedCta:'Agende sua visita'})))
test('presenter variants and disabled presenter',()=>{assert.match(buildSmartTourPrompt({generation:normalizeGeneration({mode:'guided_tour',presenterGender:'female'}),property,selectedCta:'CTA'}),/female real estate agent/);assert.match(buildSmartTourPrompt({generation:normalizeGeneration({mode:'guided_tour',presenterGender:'male'}),property,selectedCta:'CTA'}),/male real estate agent/);assert.match(buildSmartTourPrompt({generation:normalizeGeneration({mode:'narrated_tour'}),property,selectedCta:'CTA'}),/Do not create any presenter/)})
test('language modules',()=>{for(const [code,label] of [['pt-BR','Brazilian Portuguese'],['en-US','English'],['es','Spanish']]) assert.match(buildSmartTourPrompt({generation:normalizeGeneration({mode:'narrated_tour',language:code}),property,selectedCta:'CTA'}),new RegExp(label))})
test('context omits empty fields and protects CTA/phone',()=>{const value=buildPropertyContext({...property,price:''},'Fale comigo','(11) 99999-0000');assert.doesNotMatch(value,/Price:/);assert.match(value,/Fale comigo/);assert.match(value,/99999-0000/)})
test('request preserves order, rejects seven and duplicates',()=>{const base={clientRequestId:'abc',imagePaths:['u/1.jpg','u/2.jpg'],imageOrder:['u/1.jpg','u/2.jpg'],property,generation:normalizeGeneration({mode:'narrated_tour'}),selectedCta:'CTA',includeProfessionalPhone:false,language:'pt-BR'};assert.deepEqual(validateSmartTourRequest(base).imageOrder,base.imageOrder);assert.throws(()=>validateSmartTourRequest({...base,imagePaths:Array.from({length:7},(_,i)=>`u/${i}.jpg`),imageOrder:Array.from({length:7},(_,i)=>`u/${i}.jpg`)}),/invalid_image_count/);assert.throws(()=>validateSmartTourRequest({...base,imagePaths:['u/1.jpg','u/1.jpg'],imageOrder:['u/1.jpg','u/1.jpg']}),/invalid_image_count/)})
test('before_after is normalized away without virtual staging',()=>assert.equal(normalizeGeneration({mode:'smart_staging',furniture:'original',stagingPresentation:'before_after'}).stagingPresentation,'final_only'))

