import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { buildGeminiOmniRequestBody } from '../../geminiOmniClient.ts'
import { buildSmartTourStructuredBriefing, buildSmartTourVideoPrompt, SMART_TOUR_NARRATION_LIBRARY } from '../index.ts'

const property = {
  purpose: 'sale',
  type: 'Apartamento',
  state: 'SP',
  city: 'São Paulo',
  district: 'Moema',
  bedrooms: '4',
  suites: '2',
  parkingSpaces: '3',
  area: '198',
  stage: 'Pronto para morar',
  price: 'R$ 2.850.000',
  condominium: 'R$ 1.200',
  iptu: 'R$ 650',
  highlights: ['Vista livre', 'Varanda gourmet', 'Próximo ao metrô'],
  description: 'Apartamento amplo com excelente distribuição.',
}
const generation = { mode: 'guided_tour', presenterGender: 'female', narration: 'enabled', captions: 'enabled', furniture: 'original', stagingPresentation: 'final_only', language: 'pt-BR' } as const
const imagePaths = Array.from({ length: 5 }, (_, index) => `user/smart-tour/request/${index + 1}.jpg`)
const build = (overrides = {}) => buildSmartTourStructuredBriefing({
  generation,
  property,
  selectedCta: 'Agende sua visita',
  phone: '(11) 98765-4321',
  imagePaths,
  language: 'pt-BR',
  ...overrides,
})

test('SmartCorretorAI builds the complete structured JSON without asking Gemini to organize data', () => {
  const briefing = build()
  assert.equal(briefing.versao, 'smart-tour-structured-briefing-v1')
  assert.equal(briefing.tarefa, 'gerar_video_smart_tour')
  assert.deepEqual(briefing.configuracoes, {
    modo: 'guided_tour', idioma: 'pt-BR', formato: '9:16', duracaoSegundos: 10,
    quantidadeImagens: 5, narracaoAtiva: true, legendasAtivas: true, ctaAtivo: true,
  })
  assert.deepEqual(briefing.imovel, {
    finalidade: 'Venda', tipo: 'Apartamento', estadoDoImovel: 'Pronto para morar',
    localizacao: { estado: 'SP', cidade: 'São Paulo', bairro: 'Moema' },
    dormitorios: '4', suites: '2', banheiros: null, vagas: '3', area: '198',
    preco: 'R$ 2.850.000', condominio: 'R$ 1.200', iptu: 'R$ 650',
    destaques: ['Vista livre', 'Varanda gourmet', 'Próximo ao metrô'],
    descricao: 'Apartamento amplo com excelente distribuição.',
  })
  assert.deepEqual(briefing.apresentador, { tipo: 'corretora', unicoHumanoAutorizado: true })
  assert.deepEqual(briefing.staging, { modo: 'original', apresentacao: 'final_only' })
  assert.deepEqual(briefing.musica, { configurada: false, instrucao: 'preservar_comportamento_atual' })
  assert.deepEqual(briefing.sequenciaDasImagens, imagePaths)
  assert.deepEqual(briefing.movimentosDesejados, ['movimento_linear_baixa_amplitude', 'pan_suave', 'push_in_minimo', 'pull_back_minimo'])
  assert.equal(briefing.regrasPreservacao.cenarioProtegido, true)
  assert.equal(briefing.regrasPreservacao.umaImagemPorCena, true)
  assert.equal(briefing.regrasPreservacao.respeitarOrdemDasImagens, true)
})

test('captions are generated by SmartCorretorAI with exact text for one caption per scene', () => {
  const briefing = build()
  assert.deepEqual(briefing.legendas, {
    ativas: true,
    cenas: [
      { cena: 1, texto: '198 m² • 4 Dormitórios • 2 Suítes' },
      { cena: 2, texto: 'Pronto para morar' },
      { cena: 3, texto: 'Vista livre' },
      { cena: 4, texto: 'Moema • São Paulo' },
      { cena: 5, texto: 'R$ 2.850.000' },
    ],
  })
  assert.deepEqual(briefing.cenas.map(scene => scene.legenda), briefing.legendas.cenas.map(caption => caption.texto))
  assert.deepEqual(briefing.cenas.map(scene => scene.imagem), imagePaths)
})

test('rule-based narration complements captions, stays short and leaves the final phone visible', () => {
  const briefing = build()
  assert.equal(briefing.narracao.ativa, true)
  assert.equal(briefing.narracao.tempoAproximadoPorCenaSegundos, 1.8)
  assert.equal(briefing.narracao.cenas.length, 5)
  for (const scene of briefing.cenas) {
    assert.notEqual(scene.narracao, scene.legenda)
    assert.ok(scene.narracao.split(/\s+/).length <= 8, scene.narracao)
  }
  assert.deepEqual(briefing.cenas.slice(0, -1).map(scene => scene.duracaoNarracaoSegundos), [1.8, 1.8, 1.8, 1.8])
  assert.equal(briefing.cenas.at(-1)?.duracaoNarracaoSegundos, 1.2)
  assert.ok(SMART_TOUR_NARRATION_LIBRARY.encerramento.includes(briefing.cenas.at(-1)?.narracao as never))
  assert.match(JSON.stringify(briefing.regrasObrigatorias), /manter o telefone visível/)
})

test('phrase library selects stable contextual variations without random output', () => {
  const first = build()
  const repeated = build()
  assert.deepEqual(first.narracao, repeated.narracao)
  const variations = new Set(Array.from({ length: 12 }, (_, index) => build({ property: { ...property, district: `Bairro ${index}` } }).narracao.cenas[0].texto))
  assert.ok(variations.size > 1)
})

test('CTA contains exactly the title and phone supplied by SmartCorretorAI', () => {
  const briefing = build({ selectedCta: 'Fale comigo — agora!', phone: '+55 (11) 98765-4321' })
  assert.deepEqual(briefing.cta, { titulo: 'Fale comigo — agora!', telefone: '+55 (11) 98765-4321' })
  assert.deepEqual(Object.keys(briefing.cta), ['titulo', 'telefone'])
})

test('disabled modules remain empty without changing staging, duration or images', () => {
  const disabled = build({
    generation: { ...generation, presenterGender: 'none', narration: 'disabled', captions: 'disabled' },
    selectedCta: '',
    phone: '(11) 98765-4321',
  })
  assert.deepEqual(disabled.apresentador, { tipo: 'nenhum', unicoHumanoAutorizado: false })
  assert.deepEqual(disabled.narracao.cenas, [])
  assert.deepEqual(disabled.legendas.cenas, [])
  assert.deepEqual(disabled.cta, { titulo: '', telefone: '' })
  assert.equal(disabled.configuracoes.duracaoSegundos, 10)
  assert.equal(disabled.configuracoes.quantidadeImagens, 5)
  assert.deepEqual(disabled.cenas.map(scene => scene.imagem), imagePaths)
  assert.ok(disabled.cenas.every(scene => scene.narracao === '' && scene.legenda === '' && scene.duracaoNarracaoSegundos === 0))
})

test('Gemini Omni receives the exact JSON as the only briefing text and remains the video generator', () => {
  const briefing = build()
  const prompt = buildSmartTourVideoPrompt(briefing)
  assert.equal(prompt, JSON.stringify(briefing))
  assert.ok(prompt.startsWith('{') && prompt.endsWith('}'))
  assert.doesNotMatch(prompt, /BRIEFING BASE COMPILADO|FASE 1|FASE 2/)
  const images = imagePaths.map((_, index) => ({ type: 'image', data: `image-${index + 1}`, mime_type: 'image/jpeg' }))
  const payload = buildGeminiOmniRequestBody(prompt, images)
  assert.equal(payload.model, 'gemini-omni-flash-preview')
  assert.deepEqual(payload.response_format, { type: 'video', duration: '10s', delivery: 'uri' })
  assert.deepEqual(payload.input.slice(0, 5), images)
  assert.deepEqual(payload.input.at(-1), { type: 'text', text: JSON.stringify(briefing) })
})

test('active generation builds JSON locally and makes only the existing Gemini Omni video call', () => {
  const source = readFileSync(new URL('../../../smart-tour-generate/index.ts', import.meta.url), 'utf8')
  assert.match(source, /buildSmartTourStructuredBriefing\(\{generation:input\.generation,property:input\.property,selectedCta:input\.selectedCta,phone,imagePaths:input\.imagePaths,language:input\.language\}\)/)
  assert.match(source, /startGeminiOmniVideo\(\{prompt,images\}\)/)
  assert.doesNotMatch(source, /orchestrateSmartTour|geminiSmartTourOrchestrator|buildSmartTourPrompt/)
  assert.equal((source.match(/startGeminiOmniVideo/g) || []).length, 2)
})
