import type { LifeScene, SupportedLanguage } from './types.ts'

const locale = (language?: SupportedLanguage) => language === 'en-US' ? 'en-US' : 'pt-BR'
const value = (input: unknown) => String(input ?? '').trim()
const present = (input: unknown, labels: Record<string, string>, language?: SupportedLanguage) => {
  const raw = value(input)
  return locale(language) === 'en-US' ? labels[raw] || raw : raw
}

const PURPOSES = Object.freeze({ Venda: 'For Sale', Locação: 'For Rent', sale: 'For Sale', rent: 'For Rent', rental: 'For Rent' })
const PROPERTY_TYPES = Object.freeze({ Apartamento: 'Apartment', Casa: 'House', Cobertura: 'Penthouse', 'Studio / Loft': 'Studio / Loft', 'Terreno / Lote': 'Land / Lot', Comercial: 'Commercial Property', us_single_family_home: 'Single-family home', us_condo: 'Condo', us_townhouse: 'Townhouse', us_multi_family: 'Multi-family home', us_apartment: 'Apartment', us_studio: 'Studio', us_land_lot: 'Land / lot', us_commercial: 'Commercial property' })
const STAGES = Object.freeze({ 'Pré-lançamento': 'Pre-launch', Lançamento: 'Launch', 'Em obras': 'Under construction', 'Pronto para morar': 'Move-in ready', 'Disponível já': 'Available now', Vago: 'Vacant' })
const CTAS = Object.freeze({ 'Agende sua visita': 'Schedule your visit', 'Saiba mais': 'Learn more', 'Entre em contato agora': 'Contact us now', 'Fale comigo': 'Get in touch', 'Conheça as condições': 'Explore the terms', 'Quero informações': 'Request information', 'Chamar no WhatsApp': 'Message on WhatsApp' })
const LIFE_PROFILES_PT_BR: Record<LifeScene, string> = Object.freeze({ young: 'jovens', young_dog: 'jovens com cachorro', young_cat: 'jovens com gato', adult: 'adultos', adult_dog: 'adultos com cachorro', adult_cat: 'adultos com gato', senior: 'idosos', senior_dog: 'idosos com cachorro', senior_cat: 'idosos com gato' })
const LIFE_PROFILES_EN_US: Record<LifeScene, string> = Object.freeze({ young: 'Young adults', young_dog: 'Young adults with a dog', young_cat: 'Young adults with a cat', adult: 'Adults', adult_dog: 'Adults with a dog', adult_cat: 'Adults with a cat', senior: 'Seniors', senior_dog: 'Seniors with a dog', senior_cat: 'Seniors with a cat' })
const METRICS = Object.freeze({ bedrooms: 'bedrooms', suites: 'suites', parkingSpaces: 'parking spaces', area: 'sq ft' })

// Mirrors the approved Virtual Staging catalog without importing frontend code.
const HIGHLIGHTS = Object.freeze({
  'Próximo ao metrô': 'Near public transit', 'Próximo ao comércio': 'Near shops', 'Próximo a escolas': 'Near schools', 'Próximo a universidades': 'Near universities', 'Próximo a hospitais': 'Near hospitals', 'Próximo a parques': 'Near parks', 'Próximo ao shopping': 'Near shopping', 'Próximo à praia': 'Near the beach', 'Próximo ao aeroporto': 'Near the airport', 'Próximo ao centro': 'Near downtown', 'Fácil acesso': 'Easy access', 'Próximo a rodovias': 'Near major highways', 'Rua tranquila': 'Quiet street', 'Bairro valorizado': 'Desirable neighborhood', 'Região nobre': 'Prestigious area', 'Vista livre': 'Unobstructed view', 'Frente para praça': 'Facing a public square',
  'Lazer completo': 'Full leisure amenities', Piscina: 'Swimming pool', 'Piscina aquecida': 'Heated pool', Academia: 'Fitness center', Churrasqueira: 'Barbecue area', 'Espaço gourmet': 'Gourmet entertaining area', 'Salão de festas': 'Party room', 'Salão de jogos': 'Game room', Playground: 'Playground', Brinquedoteca: "Children's playroom", Coworking: 'Coworking space', 'Pet Place': 'Pet area', 'Quadra esportiva': 'Sports court', 'Quadra de tênis': 'Tennis court', Sauna: 'Sauna', Spa: 'Spa', Cinema: 'Screening room', 'Mini mercado': 'On-site convenience store', Bicicletário: 'Bike storage', 'Lavanderia coletiva': 'Shared laundry', 'Portaria 24h': '24-hour concierge', 'Portaria 24 horas': '24-hour concierge', 'Condomínio clube': 'Club community', 'Piscina e academia': 'Pool and fitness center', 'Segurança 24h': '24-hour security', Monitoramento: 'Security monitoring', Elevador: 'Elevator', Gerador: 'Backup generator', 'Energia solar': 'Solar energy',
  'Alto padrão': 'Luxury', Reformado: 'Renovated', Novo: 'New', 'Nunca habitado': 'Never occupied', 'Semi mobiliado': 'Partially furnished', Mobiliado: 'Furnished', 'Móveis planejados': 'Custom built-in cabinetry', Closet: 'Walk-in closet', Escritório: 'Office', 'Home office': 'Home office', Lavabo: 'Powder room', 'Suíte master': 'Primary suite', 'Cozinha americana': 'Open-concept kitchen', Despensa: 'Pantry', 'Área de serviço': 'Laundry area', Dependência: 'Staff quarters', 'Varanda gourmet': 'Gourmet balcony', Sacada: 'Balcony', 'Sacada envidraçada': 'Enclosed glass balcony', Terraço: 'Terrace', Quintal: 'Backyard', Jardim: 'Garden', 'Piscina privativa': 'Private pool', Jacuzzi: 'Hot tub', 'Churrasqueira privativa': 'Private barbecue area', 'Piso porcelanato': 'Porcelain tile flooring', 'Piso vinílico': 'Vinyl flooring', Mármore: 'Marble', Granito: 'Granite', 'Pé-direito alto': 'High ceilings', 'Excelente ventilação': 'Excellent ventilation', 'Sol da manhã': 'Morning sun', 'Sol da tarde': 'Afternoon sun', 'Iluminação natural': 'Natural light', 'Ambientes integrados': 'Open-plan living', 'Vista panorâmica': 'Panoramic view', 'Vista permanente': 'Protected view', 'Vista para o mar': 'Ocean view', 'Vista para parque': 'Park view', 'Vista para cidade': 'City view', 'Ar-condicionado': 'Air conditioning', 'Fechadura eletrônica': 'Smart lock', 'Acabamento premium': 'Premium finishes',
  'Vagas demarcadas': 'Assigned parking spaces', 'Vaga coberta': 'Covered parking', 'Box privativo': 'Private storage unit', 'Carregador para veículo elétrico': 'EV charger', 'Aquecimento solar': 'Solar water heating', 'Reuso de água': 'Water reuse system', 'Preparação para carro elétrico': 'EV-ready infrastructure',
  'Casa em condomínio fechado': 'Home in a gated community', 'Casa térrea': 'Single-story home', Sobrado: 'Two-story home', 'Casa em rua aberta': 'Home on a public street', 'Área gourmet': 'Gourmet entertaining area', Edícula: 'Detached guest house',
  Recepção: 'Reception area', Copa: 'Kitchenette', 'Sala de reunião': 'Meeting room', 'Excelente visibilidade': 'Excellent visibility', 'Frente para avenida': 'Fronting a major avenue', 'Alto fluxo': 'High traffic', 'Ideal para clínica': 'Ideal for a medical practice', 'Ideal para escritório': 'Ideal for an office', 'Ideal para loja': 'Ideal for retail', 'Localização estratégica': 'Strategic location', 'Alto fluxo de pessoas': 'High foot traffic', Estacionamento: 'Parking', Vitrine: 'Storefront display window', 'Salas privativas': 'Private offices', Acessibilidade: 'Accessibility', 'Pronto para uso': 'Move-in ready', 'Zoneamento comercial': 'Commercial zoning', 'Internet de alta velocidade': 'High-speed internet', 'Cabeamento estruturado': 'Structured cabling', 'Piso elevado': 'Raised flooring', 'Energia trifásica': 'Three-phase power', 'Sala de reuniões': 'Conference room', 'Banheiros privativos': 'Private restrooms', Depósito: 'Storage room', Refeitório: 'Break room', 'Controle de acesso': 'Access control', 'Monitoramento por câmeras': 'Security camera monitoring', 'Estacionamento para clientes': 'Customer parking', 'Acesso para carga e descarga': 'Loading and unloading access', Doca: 'Loading dock', 'Ponto para carregamento de carro elétrico': 'EV charging point', 'Próximo ao transporte público': 'Near public transportation', 'Fácil acesso às principais vias': 'Easy access to major routes', 'Ideal para coworking': 'Ideal for coworking', 'Ideal para logística': 'Ideal for logistics', 'Recém-reformado': 'Recently renovated',
  Plano: 'Level lot', Esquina: 'Corner lot', Murado: 'Walled', 'Documentação regular': 'Clear documentation', 'Alto potencial construtivo': 'High development potential', 'Zoneamento residencial': 'Residential zoning', 'Excelente investimento': 'Excellent investment opportunity', 'Rua asfaltada': 'Paved street', 'Infraestrutura completa': 'Full infrastructure', 'Rede de água': 'Water service', 'Rede elétrica': 'Electric service', 'Área valorizada': 'Highly desirable area',
})

export const presentPurpose = (input: unknown, language?: SupportedLanguage) => present(input, PURPOSES, language)
export const presentPropertyType = (input: unknown, language?: SupportedLanguage) => present(input, PROPERTY_TYPES, language)
export const presentStage = (input: unknown, language?: SupportedLanguage) => present(input, STAGES, language)
export const presentCta = (input: unknown, language?: SupportedLanguage) => present(input, CTAS, language)
export const presentLifeProfile = (input: unknown, language?: SupportedLanguage) => {
  const raw = value(input)
  const profiles = locale(language) === 'en-US' ? LIFE_PROFILES_EN_US : LIFE_PROFILES_PT_BR
  return profiles[raw as LifeScene] || raw
}
export const presentHighlight = (input: unknown, language?: SupportedLanguage) => {
  const raw = value(input)
  if (locale(language) === 'en-US' && raw.startsWith('us_')) return raw.slice(3).split('_').map(part => `${part.charAt(0).toUpperCase()}${part.slice(1)}`).join(' ')
  return present(raw, HIGHLIGHTS, language)
}
export const presentHighlights = (inputs: unknown, language?: SupportedLanguage) => Array.isArray(inputs) ? inputs.map(item => presentHighlight(item, language)).filter(Boolean) : []
export const presentMetricLabel = (metric: keyof typeof METRICS, language?: SupportedLanguage) => locale(language) === 'en-US' ? METRICS[metric] : ({ bedrooms: 'dormitórios', suites: 'suítes', parkingSpaces: 'vagas', area: 'm²' } as const)[metric]
