import {supabase} from '../../src/lib/supabase'
import {writeProductDraft,readProductDraft} from '../../src/lib/product-draft'
import {verifyVideoUploads} from '../../src/lib/smart-tour-auth-recovery'
const ref='lymiddkmeyikgtyxpyup'
if(import.meta.env.MODE!=='staging'||import.meta.env.VITE_SUPABASE_URL!==`https://${ref}.supabase.co`)throw Error('staging_only')
const output=document.getElementById('result')
const show=value=>{output.textContent=JSON.stringify(value,null,2)}
async function account(){const {data,error}=await supabase.auth.getUser();if(error||!['admin-pr1-common-20260915@example.test','admin-pr1-admin-20260915@example.test'].includes(data?.user?.email))throw Error('Entre com uma conta sintética autorizada de staging.');return data.user}
async function prepare(){const user=await account(),requestId=crypto.randomUUID(),paths=[];const canvas=document.createElement('canvas');canvas.width=64;canvas.height=64;const ctx=canvas.getContext('2d');ctx.fillStyle='#5b82c2';ctx.fillRect(0,0,64,64);const image=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));for(let n=1;n<=5;n++){const path=`${user.id}/smart-tour/${requestId}/0${n}.png`;const {error}=await supabase.storage.from('studio-videos').upload(path,image,{contentType:'image/png'});if(error)throw Error('synthetic_upload_failed');paths.push(path)}const uploads={requestId,paths,savedAt:Date.now()};const ok=writeProductDraft(sessionStorage,{productKey:'video-imobiliario',schemaVersion:1,userId:user.id,data:{activeInputFlow:'images',property:{purpose:'sale',type:'Apartamento',city:'Cidade de Teste',state:'SP',district:'Bairro Sintético',bedrooms:'2',suites:'1',parkingSpaces:'1',area:'100',highlights:[]},generation:{presenterGender:'female',presenterSpeechMode:'custom',presenterCustomSpeech:'Este é um briefing sintético para validar a retomada.',narration:'enabled',captions:'disabled'},ctaEnabled:false,cta:'',includePhone:false,conversation:{activeQuestionId:'review',history:[]},imageMetadata:paths.map((_,order)=>({name:`foto-${order+1}.png`,size:image.size,type:'image/png',lastModified:0,order})),uploads,resumeAfterLogin:true}});if(!ok)throw Error('draft_not_saved');sessionStorage.setItem('pr2-staging-photo-fixture',JSON.stringify({owner:user.id,uploads}));show({realAuth:true,syntheticPhotosUploaded:paths.length,briefingSaved:ok,generationCalls:0})}
async function check(){const user=await account();const fixture=JSON.parse(sessionStorage.getItem('pr2-staging-photo-fixture'));if(!fixture)throw Error('fixture_missing');const own=fixture.owner===user.id;const folder=`${fixture.owner}/smart-tour/${fixture.uploads.requestId}`;const {data,error}=await supabase.storage.from('studio-videos').list(folder,{limit:10});let verified=false;if(own){await verifyVideoUploads(supabase,fixture.uploads,user.id);verified=true}const download=await supabase.storage.from('studio-videos').download(fixture.uploads.paths[0], {}, { cache: 'no-store' });show({realAuth:true,sameAccount:own,listedPhotos:data?.length||0,listError:!!error,downloadAllowed:!download.error&&!!download.data,downloadCachePolicy:'no-store',applicationReuseVerified:verified,generationCalls:0})}
async function invalidate(){await account();const {data}=await supabase.auth.getSession();const response=await fetch(`https://${ref}.supabase.co/auth/v1/logout?scope=local`,{method:'POST',headers:{apikey:import.meta.env.VITE_SUPABASE_ANON_KEY,Authorization:'Bearer '+data.session.access_token}});if(!response.ok)throw Error('session_revoke_failed');location.assign('/smart-tour-ai')}
for(const [id,action] of [['prepare',prepare],['check',check],['invalidate',invalidate]])document.getElementById(id).onclick=()=>action().catch(error=>show({error:error.message}))
