export default Object.freeze({
  common: Object.freeze({
    continue: 'Continue',
    cancel: 'Cancel',
    back: 'Back',
    save: 'Save',
    loading: 'Loading...',
  }),
  brand: Object.freeze({
    name: 'SNETIA',
  }),
  login: Object.freeze({
    hero: Object.freeze({
      title: 'Create complete marketing campaigns in seconds',
      description: 'Banners, videos, and copy ready for every social network, automated with AI.',
      benefits: Object.freeze({
        faster: '5x faster than hiring a designer',
        formats: 'Formats for every social network',
        copy: 'Persuasive copy generated by AI',
      }),
    }),
    title: 'Sign in to your account',
    resumeVideo: 'Sign in again with the same account to resume your Real Estate Video brief. Once signed in, review and confirm; no generation will be resubmitted automatically.',
    noAccount: "Don't have an account?",
    signUp: 'Sign up for free',
    or: 'or',
    email: Object.freeze({
      label: 'Email',
      placeholder: 'you@email.com',
      required: 'Email is required',
      invalid: 'Invalid email address',
    }),
    password: Object.freeze({
      label: 'Password',
      required: 'Password is required',
    }),
    forgotPassword: 'Forgot your password?',
    submit: 'Sign in',
    resend: Object.freeze({
      title: "Haven't confirmed your email yet?",
      description: 'You can request new instructions. The response will be the same regardless of the account status.',
      button: 'Resend confirmation email',
    }),
  }),
  social: Object.freeze({
    instagram: 'Instagram',
    facebook: 'Facebook',
    tiktok: 'TikTok',
  }),
  footer: Object.freeze({
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    navigationLabel: 'Footer',
    cookiePreferences: 'Cookie preferences',
    support: 'Support',
  }),
})
