import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import BrandMark from '../components/brand/BrandMark'
import { BRAND } from '../config/brand'

export default function Privacidade() {
  return <div className="min-h-screen bg-gray-50"><div className="mx-auto max-w-3xl px-6 py-12">
    <div className="mb-10 flex items-center justify-between"><Link to="/" className="flex items-center gap-2 text-sm text-gray-500 hover:text-gray-700"><ArrowLeft className="w-4 h-4" />Voltar</Link><div className="flex items-center gap-2"><BrandMark size={28} decorative /><span className="font-bold text-gray-900">{BRAND.name}</span></div></div>
    <article className="card p-8"><h1 className="mb-2 text-3xl font-extrabold text-gray-900">Política de Privacidade</h1><p className="mb-8 text-sm text-gray-400">Última atualização: Outubro de 2026</p>
      <div className="prose prose-gray max-w-none space-y-6 text-sm leading-relaxed text-gray-600">
        <Section title="1. Visão geral"><p>A {BRAND.name} trata dados pessoais para fornecer uma plataforma de marketing imobiliário com IA. Esta Política explica as categorias de dados, finalidades e opções disponíveis. Para dúvidas, escreva para <a href={`mailto:${BRAND.supportEmail}`} className="text-primary-600 hover:underline">{BRAND.supportEmail}</a>.</p></Section>
        <Section title="2. Dados que podemos tratar"><p><strong>Conta e perfil:</strong> nome, display name, e-mail, telefone ou WhatsApp, dados de autenticação e, quando usado, dados necessários à autenticação Google. Senhas são tratadas pelo sistema de autenticação; não afirmamos armazenamento em texto puro. Quando o Google OAuth é escolhido, solicitamos apenas os escopos de identidade, e-mail e perfil, sem acesso a Gmail, Drive, contatos ou Calendar.</p><p className="mt-2"><strong>Dados profissionais:</strong> no Brasil, CRECI, tipo F/J, número, UF e imobiliária ou empresa quando informados; nos Estados Unidos, nome de divulgação, license number, state e função profissional quando aplicável.</p><p className="mt-2"><strong>Imóveis e campanhas:</strong> descrição, finalidade, características, diferenciais, preço, condições, endereço ou localização, fotos, arquivos, textos, prompts, briefings e mídia gerada. Localização pode incluir, no Brasil, UF, cidade e bairro; nos Estados Unidos, state, county, city, ZIP Code e neighborhood/community.</p><p className="mt-2"><strong>Uso e segurança:</strong> logs, IP, navegador ou dispositivo, eventos técnicos, segurança, prevenção a fraude e abuso, saldo e consumo de Smart Tokens, histórico de gerações e status de processamento.</p></Section>
        <Section title="3. Finalidades e fundamentos"><p>Usamos dados para executar o serviço e o contrato, autenticar contas, gerar e entregar materiais, administrar planos e Smart Tokens, atender solicitações, cumprir obrigações legais, manter segurança e prevenir fraude. Quando necessário, usamos consentimento; também podemos tratar dados por legítimo interesse ou obrigação legal, conforme aplicável.</p></Section>
        <Section title="4. Pagamentos"><p>Pagamentos são processados pela Stripe. A {BRAND.name} pode armazenar referências e dados de transação necessários ao serviço, suporte, segurança e obrigações legais, mas não afirma armazenar o número completo do cartão quando ele é tratado pela Stripe.</p></Section>
        <Section title="5. Publicação social"><p>Em recursos compatíveis, podemos tratar dados necessários para conectar e publicar em Instagram e Facebook, inclusive identificadores de conta, autorização ou tokens protegidos, mídia selecionada, legenda, destino e status de publicação. A Meta pode processar dados conforme suas próprias regras. TikTok somente será tratado se e quando a integração estiver efetivamente disponibilizada.</p></Section>
        <Section title="6. Provedores e transferências"><p>Conforme o recurso usado, podemos recorrer a Supabase, Vercel, Stripe, Resend, OpenAI, Google/Gemini, Creatomate e Meta como provedores ou processadores. A autenticação pode usar Supabase Auth e o e-mail transacional pode ser enviado por Supabase Auth ou, quando aplicável, Resend. Alguns provedores podem processar dados em outros países. Aplicamos mecanismos contratuais, técnicos e legais apropriados ao contexto, sem afirmar certificações ou garantias que não existam.</p></Section>
        <Section title="7. Retenção e segurança"><p>Retemos dados enquanto a conta estiver ativa, enquanto forem necessários para prestar o serviço, cumprir obrigações legais, resolver disputas, auditar, prevenir fraude ou manter segurança. Depois, podemos excluir ou anonimizar dados quando apropriado e permitido. Adotamos medidas razoáveis de segurança, mas nenhum sistema é absolutamente seguro.</p></Section>
        <Section title="8. Direitos e crianças"><p>Usuários no Brasil podem exercer os direitos previstos pela LGPD. Usuários nos Estados Unidos podem ter direitos adicionais que variam conforme o estado e a lei aplicável. Solicitações podem ser enviadas para {BRAND.supportEmail}. A Plataforma é direcionada a profissionais e adultos e não é destinada a crianças.</p></Section>
        <Section title="9. Atualizações"><p>Podemos atualizar esta Política para refletir mudanças legais, técnicas ou operacionais. A versão vigente ficará disponível nesta página.</p></Section>
      </div>
    </article><p className="mt-8 text-center text-xs text-gray-400">© 2026 {BRAND.name} · <Link to="/termos" className="hover:underline">Termos de Uso</Link></p>
  </div></div>
}

function Section({ title, children }) { return <section><h2 className="mb-2 text-lg font-bold text-gray-800">{title}</h2>{children}</section> }
