import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import BrandMark from '../components/brand/BrandMark'
import { BRAND } from '../config/brand'

export default function TermosDeUso() {
  return <div className="min-h-screen bg-gray-50"><div className="mx-auto max-w-3xl px-6 py-12">
    <div className="mb-10 flex items-center justify-between"><Link to="/" className="flex items-center gap-2 text-sm text-gray-500 hover:text-gray-700"><ArrowLeft className="w-4 h-4" />Voltar</Link><div className="flex items-center gap-2"><BrandMark size={28} decorative /><span className="font-bold text-gray-900">{BRAND.name}</span></div></div>
    <article className="card p-8"><h1 className="mb-2 text-3xl font-extrabold text-gray-900">Termos de Uso</h1><p className="mb-8 text-sm text-gray-400">Última atualização: Outubro de 2026</p>
      <div className="prose prose-gray max-w-none space-y-6 text-sm leading-relaxed text-gray-600">
        <Section title="1. Aceitação e escopo"><p>Ao criar uma conta, acessar ou usar a {BRAND.name}, você concorda com estes Termos e com a <Link to="/privacidade" className="text-primary-600 hover:underline">Política de Privacidade</Link>. Se não concordar, não utilize a Plataforma.</p><p className="mt-2">A {BRAND.name} é uma plataforma SaaS de marketing imobiliário com inteligência artificial, voltada a profissionais e empresas, disponível para operações no Brasil e nos Estados Unidos, com conteúdos em PT-BR e EN-US conforme o recurso.</p></Section>
        <Section title="2. Recursos da Plataforma"><p>A Plataforma pode criar textos, imagens, banners, carrosséis, vídeos, roteiros e materiais de transformação visual ou virtual staging a partir de informações e materiais enviados pelo usuário. Recursos, formatos e disponibilidade podem variar por mercado, plano, saldo, oferta e capacidade técnica.</p><p className="mt-2">Quando disponibilizada, a publicação direta pode ocorrer em Instagram e Facebook. TikTok somente poderá ser oferecido quando a integração estiver efetivamente disponível; estes Termos não prometem recurso futuro.</p></Section>
        <Section title="3. Publicação em plataformas de terceiros"><p>Cada publicação exige a escolha do conteúdo, destino e confirmação do usuário. Uma conexão de conta não inicia publicação automaticamente. Instagram, Facebook, Meta e outras plataformas podem limitar, atrasar, rejeitar, remover ou interromper conteúdo ou integrações; pode haver sucesso parcial por plataforma. A {BRAND.name} não garante aprovação, disponibilidade contínua ou permanência de publicações externas.</p></Section>
        <Section title="4. Conta e segurança"><p>O usuário deve ter capacidade legal para contratar, fornecer informações corretas, proteger suas credenciais e comunicar uso não autorizado. É responsável pelas atividades realizadas em sua conta. A {BRAND.name} pode suspender ou encerrar contas em caso de fraude, abuso, risco de segurança ou violação destes Termos.</p></Section>
        <Section title="5. Responsabilidade por conteúdo e IA"><p>O usuário declara possuir os direitos, licenças e autorizações sobre fotos, imagens, marcas, textos, vídeos e demais materiais enviados ou publicados. É proibido usar a Plataforma para fraude, conteúdo ilegal, violação de direitos, spam, abuso ou acesso indevido.</p><p className="mt-2">Conteúdo gerado por IA pode conter erros, omissões ou imprecisões e deve ser revisado antes do uso. O usuário é responsável por verificar imóvel, preço, endereço, condições comerciais, identificação profissional, CRECI ou license, e demais dados antes de publicar. A Plataforma não garante venda, lead, alcance, engajamento ou resultado comercial.</p></Section>
        <Section title="6. Planos, Smart Tokens e pagamentos"><p>Planos podem ser recorrentes; recargas ou compras avulsas podem estar disponíveis conforme a oferta. Smart Tokens são capacidade de uso interna, não têm valor monetário externo, não são transferíveis nem conversíveis em dinheiro e são consumidos conforme o produto e o catálogo aplicável, inclusive campanhas de texto avulsas.</p><p className="mt-2">No Brasil, os planos atuais são START R$127/mês, PRO R$217/mês e ELITE R$547/mês; recargas avulsas incluem 2.000 Smart Tokens — R$ 49,90 e 4.000 Smart Tokens — R$ 97,90, que expiram em 30 dias. Nos Estados Unidos, os planos atuais são START US$24.90/mês, PRO US$39.90/mês e ELITE US$99.90/mês; compras avulsas incluem 2.000 Smart Tokens — US$9.90 e 4.000 Smart Tokens — US$19.90, que também expiram em 30 dias.</p><p className="mt-2">Créditos promocionais ou trial podem existir segundo a oferta vigente, sem obrigação de manter quantidade específica. Preços podem variar por mercado, em BRL no Brasil e USD nos Estados Unidos. A Stripe é o provedor de pagamento atualmente utilizado.</p><p className="mt-2">Assinaturas podem renovar até o cancelamento pela conta ou pelo portal da Stripe. Pagamentos já processados, impostos, taxas e reembolsos seguem a legislação aplicável e as regras apresentadas na contratação.</p></Section>
        <Section title="7. Propriedade intelectual"><p>A Plataforma, sua marca, tecnologia, código, modelos, layout e materiais internos pertencem à {BRAND.name} ou a seus licenciantes. Observadas as regras aplicáveis, o usuário recebe licença limitada para usar os materiais gerados em suas atividades profissionais, permanecendo responsável pelos direitos sobre seus insumos e publicações.</p></Section>
        <Section title="8. Terceiros, disponibilidade e limitações"><p>A Plataforma pode depender de provedores como Supabase, Vercel, Stripe, Resend, OpenAI, Google/Gemini, Creatomate e Meta, quando aplicável ao recurso. Esses serviços possuem regras próprias e podem sofrer manutenção, indisponibilidade ou alterações. Na máxima medida permitida pela lei aplicável, a {BRAND.name} não responde por danos indiretos, lucros cessantes, perda de oportunidade, falha de terceiro ou uso incorreto pelo usuário.</p></Section>
        <Section title="9. Alterações e lei aplicável"><p>Podemos atualizar estes Termos para refletir mudanças legais, operacionais ou de produto. A versão atual ficará nesta página. A legislação aplicável será determinada conforme a relação, o mercado e as normas obrigatórias pertinentes, sem prejuízo dos direitos que não possam ser afastados.</p></Section>
        <Section title="10. Contato"><p>Envie dúvidas sobre estes Termos para <a href={`mailto:${BRAND.supportEmail}`} className="text-primary-600 hover:underline">{BRAND.supportEmail}</a>.</p></Section>
      </div>
    </article><p className="mt-8 text-center text-xs text-gray-400">© 2026 {BRAND.name} · <Link to="/privacidade" className="hover:underline">Política de Privacidade</Link></p>
  </div></div>
}

function Section({ title, children }) { return <section><h2 className="mb-2 text-lg font-bold text-gray-800">{title}</h2>{children}</section> }
