import type {
  StudioHeroBrainSmartMotionContract,
  StudioHeroMotionMockExecutionResult,
  StudioHeroMotionValidationResult,
} from './contract.ts'
import { selectStudioHeroMotionMomentsV2, type StudioHeroMotionCandidateMoment } from './brain-v2.ts'
import { executeStudioHeroMotionMockPlan } from './mock-executor.ts'
import { validateStudioHeroMotionContract } from './validator.ts'

const originalSampleVideoDurationSeconds = 190

export const studioHeroMotionSampleMomentsV2: StudioHeroMotionCandidateMoment[] = [
  {
    id: 'abertura-sala-principal',
    environmentId: 'sala',
    environmentType: 'sala',
    label: 'Abertura na sala principal',
    sourceStartSeconds: 3,
    sourceEndSeconds: 22,
    visualInterestScore: 95,
    openingStrength: 100,
    closingStrength: 58,
    preferredDurationSeconds: 18,
  },
  {
    id: 'caminhada-sala-cozinha',
    environmentId: 'circulacao',
    environmentType: 'outro',
    label: 'Deslocamento entre sala e cozinha',
    sourceStartSeconds: 22,
    sourceEndSeconds: 34,
    visualInterestScore: 28,
    openingStrength: 12,
    closingStrength: 8,
    hasLongCorridor: true,
    isLongWalk: true,
    isEnvironmentTransition: true,
    shouldKeepForContinuity: true,
    preferredDurationSeconds: 3.5,
  },
  {
    id: 'cozinha-planejada',
    environmentId: 'cozinha',
    environmentType: 'cozinha',
    label: 'Cozinha planejada',
    sourceStartSeconds: 34,
    sourceEndSeconds: 53,
    visualInterestScore: 89,
    openingStrength: 68,
    closingStrength: 52,
    preferredDurationSeconds: 18,
  },
  {
    id: 'passagem-cozinha-quartos',
    environmentId: 'transicao',
    environmentType: 'outro',
    label: 'Passagem para area intima',
    sourceStartSeconds: 53,
    sourceEndSeconds: 64,
    visualInterestScore: 34,
    openingStrength: 10,
    closingStrength: 12,
    hasDoorTransition: true,
    isEnvironmentTransition: true,
    isLongWalk: true,
    shouldKeepForContinuity: true,
    preferredDurationSeconds: 3,
  },
  {
    id: 'quarto-principal',
    environmentId: 'quarto',
    environmentType: 'quarto',
    label: 'Dormitorio principal',
    sourceStartSeconds: 64,
    sourceEndSeconds: 83,
    visualInterestScore: 87,
    openingStrength: 60,
    closingStrength: 64,
    preferredDurationSeconds: 16,
  },
  {
    id: 'caminhada-quarto-banheiro',
    environmentId: 'transicao-area-intima',
    environmentType: 'outro',
    label: 'Transicao para banheiro',
    sourceStartSeconds: 83,
    sourceEndSeconds: 91,
    visualInterestScore: 32,
    openingStrength: 10,
    closingStrength: 16,
    hasDoorTransition: true,
    isEnvironmentTransition: true,
    isLongWalk: true,
    shouldKeepForContinuity: true,
    preferredDurationSeconds: 2.5,
  },
  {
    id: 'banheiro',
    environmentId: 'banheiro',
    environmentType: 'banheiro',
    label: 'Banheiro',
    sourceStartSeconds: 91,
    sourceEndSeconds: 108,
    visualInterestScore: 78,
    openingStrength: 42,
    closingStrength: 48,
    preferredDurationSeconds: 13,
  },
  {
    id: 'trecho-parado-repetido',
    environmentId: 'banheiro',
    environmentType: 'banheiro',
    label: 'Momento parado repetido',
    sourceStartSeconds: 108,
    sourceEndSeconds: 116,
    visualInterestScore: 70,
    openingStrength: 45,
    closingStrength: 40,
    hasStaticCamera: true,
    isRepeatedContent: true,
  },
  {
    id: 'deslocamento-area-servico',
    environmentId: 'circulacao-servico',
    environmentType: 'outro',
    label: 'Deslocamento para area de servico',
    sourceStartSeconds: 116,
    sourceEndSeconds: 126,
    visualInterestScore: 30,
    openingStrength: 14,
    closingStrength: 18,
    hasLongCorridor: true,
    isEnvironmentTransition: true,
    isLongWalk: true,
    shouldKeepForContinuity: true,
    preferredDurationSeconds: 3,
  },
  {
    id: 'lavanderia',
    environmentId: 'lavanderia',
    environmentType: 'lavanderia',
    label: 'Lavanderia e serviço',
    sourceStartSeconds: 126,
    sourceEndSeconds: 141,
    visualInterestScore: 72,
    openingStrength: 32,
    closingStrength: 38,
    preferredDurationSeconds: 11,
  },
  {
    id: 'passagem-varanda',
    environmentId: 'transicao-varanda',
    environmentType: 'outro',
    label: 'Passagem para varanda',
    sourceStartSeconds: 141,
    sourceEndSeconds: 150,
    visualInterestScore: 36,
    openingStrength: 18,
    closingStrength: 25,
    hasDoorTransition: true,
    isEnvironmentTransition: true,
    isLongWalk: true,
    shouldKeepForContinuity: true,
    preferredDurationSeconds: 3,
  },
  {
    id: 'varanda',
    environmentId: 'varanda',
    environmentType: 'varanda',
    label: 'Varanda',
    sourceStartSeconds: 150,
    sourceEndSeconds: 168,
    visualInterestScore: 92,
    openingStrength: 74,
    closingStrength: 86,
    preferredDurationSeconds: 15,
  },
  {
    id: 'vista-livre',
    environmentId: 'vista',
    environmentType: 'vista',
    label: 'Vista livre',
    sourceStartSeconds: 168,
    sourceEndSeconds: 179,
    visualInterestScore: 86,
    openingStrength: 55,
    closingStrength: 80,
    preferredDurationSeconds: 9,
  },
  {
    id: 'encerramento-corretor',
    environmentId: 'encerramento',
    environmentType: 'encerramento',
    label: 'Encerramento da visita',
    sourceStartSeconds: 179,
    sourceEndSeconds: 188,
    visualInterestScore: 84,
    openingStrength: 45,
    closingStrength: 100,
    preferredDurationSeconds: 7,
  },
]

export const studioHeroMotionBrainV2Selection = selectStudioHeroMotionMomentsV2(studioHeroMotionSampleMomentsV2, {
  sourceDurationSeconds: originalSampleVideoDurationSeconds,
  targetDurationRangeSeconds: { min: 90, max: 125 },
  maxDurationPerEnvironmentSeconds: 18,
})

const estimatedMainReelDurationSeconds = studioHeroMotionBrainV2Selection.cuts.reduce(
  (total, cut) => total + (cut.sourceEndSeconds - cut.sourceStartSeconds),
  0,
)

export const studioHeroMotionSampleCampaign = {
  contractVersion: 'studio_hero_motion.v1',
  requestId: 'studio-hero-motion-sample-campaign-001',
  source: 'studio_hero_brain',
  target: 'smart_motion_engine',
  sourceVideo: {
    id: 'broker-video-sample-001',
    fileName: 'video-corretor-imovel-2.mp4',
    mimeType: 'video/mp4',
    durationSeconds: originalSampleVideoDurationSeconds,
  },
  campaignBrief: {
    objective: 'sale',
    propertyType: 'Apartamento',
    city: 'São Paulo',
    district: 'Vila Mariana',
    keyFeatures: ['Vista livre', 'Sala integrada', 'Cozinha planejada', 'Varanda'],
    tone: 'social',
  },
  mainReel: {
    id: 'main-reel-venda-apartamento',
    title: 'Video aprimorado - visita ao apartamento',
    aspectRatio: '9:16',
    targetDurationSeconds: Math.round(estimatedMainReelDurationSeconds),
    cuts: studioHeroMotionBrainV2Selection.cuts,
    ctaFinal: {
      text: 'AGENDE SUA VISITA',
      startSeconds: Math.max(0, estimatedMainReelDurationSeconds - 7),
      endSeconds: estimatedMainReelDurationSeconds,
      visualStyle: 'direct',
    },
    effects: [],
    finishing: {
      backgroundMusic: {
        enabled: true,
        source: 'internal_placeholder',
        volumeMode: 'auto',
        volumeLevel: 0.08,
        fadeInSeconds: 1.2,
        fadeOutSeconds: 2.2,
      },
      cta: {
        enabled: true,
        renderNow: false,
        text: 'AGENDE SUA VISITA',
        startSeconds: Math.max(0, estimatedMainReelDurationSeconds - 7),
        endSeconds: estimatedMainReelDurationSeconds,
      },
      captions: {
        enabled: true,
        renderNow: false,
        source: 'future_speech_to_text',
        language: 'pt-BR',
      },
    },
  },
  smartClips: [
    {
      id: 'smart-clip-vista',
      title: 'Vista',
      aspectRatio: '9:16',
      targetDurationSeconds: 7,
      cuts: [
        {
          id: 'clip-cut-vista',
          label: 'Vista livre',
          sourceStartSeconds: 4,
          sourceEndSeconds: 11,
        },
      ],
      tags: ['VISTA LIVRE'],
      ctaFinal: { text: 'Veja mais detalhes', visualStyle: 'clean' },
    },
    {
      id: 'smart-clip-sala',
      title: 'Sala',
      aspectRatio: '9:16',
      targetDurationSeconds: 8,
      cuts: [
        {
          id: 'clip-cut-sala',
          label: 'Sala integrada',
          sourceStartSeconds: 14,
          sourceEndSeconds: 24,
        },
      ],
      tags: ['SALA INTEGRADA'],
      ctaFinal: { text: 'Agende sua visita', visualStyle: 'direct' },
    },
    {
      id: 'smart-clip-cozinha',
      title: 'Cozinha',
      aspectRatio: '9:16',
      targetDurationSeconds: 7,
      cuts: [
        {
          id: 'clip-cut-cozinha',
          label: 'Cozinha planejada',
          sourceStartSeconds: 29,
          sourceEndSeconds: 38,
        },
      ],
      tags: ['COZINHA'],
      ctaFinal: { text: 'Conheça o imóvel', visualStyle: 'clean' },
    },
    {
      id: 'smart-clip-varanda',
      title: 'Varanda',
      aspectRatio: '9:16',
      targetDurationSeconds: 7,
      cuts: [
        {
          id: 'clip-cut-varanda',
          label: 'Varanda',
          sourceStartSeconds: 43,
          sourceEndSeconds: 53,
        },
      ],
      tags: ['VARANDA'],
      ctaFinal: { text: 'Chame para visitar', visualStyle: 'direct' },
    },
  ],
  campaignTexts: {
    headline: 'Apartamento com vista livre e varanda na Vila Mariana',
    shortCaption: 'Vista livre, sala integrada, cozinha planejada e varanda em um apartamento pronto para encantar.',
    longCaption: 'Conheça este apartamento na Vila Mariana com ambientes integrados, ótima iluminação natural, cozinha planejada e uma varanda perfeita para aproveitar a vista livre. Uma campanha pronta para Reels, WhatsApp e portais imobiliários.',
    whatsappMessage: 'Olá! Tenho um apartamento com vista livre, sala integrada, cozinha planejada e varanda na Vila Mariana. Quer receber mais detalhes ou agendar uma visita?',
    portalDescription: 'Apartamento à venda na Vila Mariana com vista livre, sala integrada, cozinha planejada e varanda. Imóvel com apresentação dinâmica ideal para quem busca praticidade, boa iluminação e localização valorizada.',
    hashtags: ['#VistaLivre', '#ApartamentoAVenda', '#VilaMariana', '#ImoveisSP', '#AgendeSuaVisita'],
    cta: 'AGENDE SUA VISITA',
  },
  metadata: {
    sample: true,
    phase: 'studio_hero_motion_phase_2_finishing_layer',
    originalDurationSeconds: originalSampleVideoDurationSeconds,
    estimatedFinalDurationSeconds: estimatedMainReelDurationSeconds,
    brainVersion: 'studio_hero_motion_brain_v2_2_improve_original_visit',
    brainRulesApplied: studioHeroMotionBrainV2Selection.rulesApplied,
    rejectedMomentIds: studioHeroMotionBrainV2Selection.rejectedMomentIds,
    renderer: 'main_reel_cut_join_with_finishing_layer',
  },
} satisfies StudioHeroBrainSmartMotionContract

export type StudioHeroMotionSampleCampaignDemoResult = {
  validation: StudioHeroMotionValidationResult
  execution: StudioHeroMotionMockExecutionResult
}

export function runStudioHeroMotionSampleCampaignDemo(): StudioHeroMotionSampleCampaignDemoResult {
  const validation = validateStudioHeroMotionContract(studioHeroMotionSampleCampaign)
  if (!validation.ok) {
    return {
      validation,
      execution: {
        requestId: studioHeroMotionSampleCampaign.requestId,
        engine: 'smart_motion_engine',
        mode: 'mock_plan_only',
        actions: [],
      },
    }
  }

  return {
    validation,
    execution: executeStudioHeroMotionMockPlan(studioHeroMotionSampleCampaign),
  }
}
