-- Migration intentionally retired before production.
-- The six-hour Virtual Staging cleanup schedule is not part of the current
-- retention policy or production rollout. No extensions, Vault integration or
-- cron job are required.
