-- Migration intentionally retired before production.
-- Short Videos already performs lifecycle cleanup in its active request and
-- recovery flows. The separate scheduled cleanup is deferred, so no database
-- extensions, Vault integration or cron job are required in this rollout.
